### ISSUE TITLE
XE7 Image

### ISSUE THREAD

**Issue by kmcgill88** [Embarcadero/InterBase-Docker#1]
Do you happen to have an XE7 image? If not, would it be possible for you to publish one? I'm working with a legacy system and it would be helpful if I could use an XE7 image to help with modernization efforts.

**Comment by lynxnake** [comment]
XE7, as well as previous versions are available with any purchase of RAD Studio

**Comment by omonien** [comment]
Why has this issue been closed? It's not about XE7 (or older) being available with a current license, it's about publishing a certain set of docker images with versions that are widely in use.

**Comment by lynxnake** [comment]
> It's not about XE7 (or older) being available with a current license, it's about publishing a certain set of docker images with versions that are widely in use.

Thanks, @omonien, I didn't get this at first sight. I will try to reach out to Embarcadero about this
